# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 16:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('attachment', models.FileField(upload_to='workover_sketch')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='OperationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OperationPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=100)),
                ('gross', models.FloatField(default=0.0)),
                ('net', models.FloatField(default=0.0)),
                ('gor', models.FloatField(default=0.0)),
                ('dfl', models.FloatField(default=0.0)),
                ('liq', models.FloatField(default=0.0)),
                ('wc', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_type', models.CharField(max_length=50)),
                ('pump_depth', models.FloatField(default=0.0)),
                ('config', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='WaterCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('normal_value', models.FloatField(default=0.0)),
                ('statues', models.CharField(choices=[('N', 'Natural flow'), ('F', 'artificial lift'), ('J', 'Injection')], default='N', max_length=1)),
                ('check_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_schedule', to='wells.Schedule')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.Field')),
                ('operations', models.ManyToManyField(to='wells.Operation')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_schedule', to='wells.Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='watercut',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.Well'),
        ),
        migrations.AddField(
            model_name='pump',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.Well'),
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.OperationName'),
        ),
        migrations.AddField(
            model_name='operation',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.OperationPerformance'),
        ),
        migrations.AddField(
            model_name='operation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
