# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_schedule_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='well',
        ),
        migrations.AddField(
            model_name='well',
            name='pump',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wells.Pump'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='statues',
            field=models.CharField(choices=[('N', 'Natural flow'), ('F', 'Artificial lift'), ('J', 'Injection')], default='N', max_length=1),
        ),
    ]
