# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0003_auto_20170908_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationperformance',
            name='sep_p',
            field=models.IntegerField(default=0),
        ),
    ]
