# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_operationperformance_sep_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='attachment',
        ),
        migrations.AddField(
            model_name='operation',
            name='sketch',
            field=models.ImageField(blank=True, null=True, upload_to='workover_sketch'),
        ),
    ]
