# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_auto_20170930_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='user_id',
            new_name='user',
        ),
    ]
