# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0006_auto_20170930_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='operation_name',
            new_name='operation',
        ),
    ]
