# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0007_auto_20170930_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='performance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.OperationPerformance'),
        ),
    ]
