# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0009_auto_20170930_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='check_id',
        ),
        migrations.AddField(
            model_name='well',
            name='check_id',
            field=models.ManyToManyField(related_name='check_schedule', to='wells.Schedule'),
        ),
        migrations.RemoveField(
            model_name='well',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='well',
            name='schedule_id',
            field=models.ManyToManyField(related_name='regular_schedule', to='wells.Schedule'),
        ),
    ]
