# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0010_auto_20171002_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watercut',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='watercut',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
