# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0012_auto_20171002_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='need_check',
            field=models.BooleanField(default=False),
        ),
    ]
